apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            name: dev
          # - cluster: cluster-name
  template:
    metadata:
      name: '{{name}}-elasticsearch'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
          namespace: logging
          name: '{{cluster}}'
      syncPolicy:
        automated:
          prune: false           
          selfHeal: true          
        syncOptions:
        - CreateNamespace=true
        
      project: default
      source:
        repoURL: https://helm.elastic.co
        targetRevision: 8.5.1
        chart: elasticsearch
        helm:
          values: |
            replicas: 1
            nodeSelector:
              karpenter.sh/capacity-type: spot

            secret:
              enabled: true
              password: "elastic"

            nodeSelector:
              type: demand 

            image: "docker.elastic.co/elasticsearch/elasticsearch"
            imageTag: "8.5.1"

            resources:
              requests:
                cpu: "200m"
                memory: "500Mi"
              limits:
                cpu: "1000m"
                memory: "2Gi"


            antiAffinity: "soft"
            volumeClaimTemplate:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 30Gi


            persistence:
              enabled: true

            protocol: https
            httpPort: 9200
            transportPort: 9300

            podSecurityContext:
              fsGroup: 1000
              runAsUser: 1000