apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            name: dev
          # - cluster: cluster-name
  template:
    metadata:
      name: '{{name}}-elasticsearch'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
          namespace: monitoring
          name: '{{cluster}}'
      syncPolicy:
        automated:
          prune: false           
          selfHeal: true          
        syncOptions:
        - CreateNamespace=true
        
      project: default
      source:
        repoURL: https://helm.elastic.co
        targetRevision: 8.5.1
        chart: elasticsearch
        helm:
          values: |
            daemonset:
            enabled: true
            extraEnvs:
              - name: "ELASTICSEARCH_USERNAME"
                valueFrom:
                  secretKeyRef:
                    name: elasticsearch-master-credentials
                    key: username
              - name: "ELASTICSEARCH_PASSWORD"
                valueFrom:
                  secretKeyRef:
                    name: elasticsearch-master-credentials
                    key: password

            filebeatConfig:
              filebeat.yml: |
                filebeat.config:
                  modules:
                    path: ${path.config}/modules.d/*.yml
                    # Reload module configs as they change:
                    reload.enabled: false


                filebeat.autodiscover:
                  providers:
                    - type: kubernetes
                      templates:
                        - condition:
                            has_fields: ['kubernetes.labels.enableElasticLogCollection']
                          config:
                            - type: container
                              paths:
                                - /var/log/containers/*-${data.kubernetes.container.id}.log
                              containers.ids:
                                -  "${data.kubernetes.container.id}"
                              multiline:
                                pattern: '^(2024/\d{2}/\d{2} \d{2}:\d{2}:\d{2}|FATAL|INFO|ERROR|WARN|DEBUG|TRACE)'
                                negate: true
                                match: after


                output.logstash:
                  hosts: ["logstash-logstash:5044"]

                processors:
                  - drop_event:
                      when:
                        contains:
                          message: "ELB-HealthChecker/2.0"

            maxUnavailable: 1

            secretMounts:
              - name: elasticsearch-master-certs
                secretName: elasticsearch-master-certs
                path: /usr/share/filebeat/certs/

            securityContext:
              runAsUser: 0
              privileged: false
            resources:
              requests:
                cpu: "10m"
                memory: "100Mi"
              limits:
                cpu: "200m"
                memory: "200Mi"


          image: "docker.elastic.co/beats/filebeat"
          imageTag: "8.5.1"