apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            name: dev
          # - cluster: cluster-name
  template:
    metadata:
      name: '{{name}}-elasticsearch'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
          namespace: monitoring
          name: '{{cluster}}'
      syncPolicy:
        automated:
          prune: false           
          selfHeal: true          
        syncOptions:
        - CreateNamespace=true
        
      project: default
      source:
        repoURL: https://helm.elastic.co
        targetRevision: 8.5.1
        chart: elasticsearch
        helm:
          values: |
            elasticsearchHosts: "https://elasticsearch-master:9200"

            replicas: 1

            image: "docker.elastic.co/kibana/kibana"
            imageTag: "8.5.1"

            resources:
              requests:
                cpu: "300m"
                memory: "300Mi"
              limits:
                cpu: "300m"
                memory: "1Gi"

            protocol: http

            serverHost: "0.0.0.0"

            httpPort: 5601

            service:
              type: ClusterIP
              loadBalancerIP: ""
              port: 5601
              nodePort: ""
              labels: {}
              annotations: {}
              loadBalancerSourceRanges: []
              httpPortName: http