apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            name: dev
          # - cluster: cluster-name
  template:
    metadata:
      name: '{{name}}-ingress-nginx'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
          namespace: ingress-nginx
          name: '{{cluster}}'
      syncPolicy:
        automated:
          prune: false           
          selfHeal: true          
        syncOptions:
        - CreateNamespace=true
        
      project: default
      source:
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.11.2
        chart: ingress-nginx
        helm:
          values: |
            controller:
              service:
                type: LoadBalancer
                annotations:
                  service.beta.kubernetes.io/aws-load-balancer-type: "nlb"