apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            name: dev
          # - cluster: cluster-name
  template:
    metadata:
      name: '{{name}}-kube-prometheus-stack'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
          namespace: monitoring
          name: '{{cluster}}'
      syncPolicy:
        automated:
          prune: false           
          selfHeal: true          
        syncOptions:
        - CreateNamespace=true
        
      project: default
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 65.3.1
        chart: kube-prometheus-stack
        helm:
          values: |
            