apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metric-server
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            name: dev
          # - cluster: cluster-name
  template:
    metadata:
      name: '{{name}}-metric-server'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
          namespace: kube-system
          name: '{{cluster}}'
      syncPolicy:
        automated:
          prune: false           
          selfHeal: true          
        syncOptions:
        - CreateNamespace=true
        - Prune=false
      project: default
      source:
        repoURL: https://kubernetes-sigs.github.io/metrics-server/
        targetRevision: 3.12.2
        chart: metrics-server
        helm:
          values: |
            resources:
              requests:
                cpu: 100m
                memory: 200Mi