apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metric-server
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            name: dev
          # - cluster: cluster-name
  template:
    metadata:
      name: '{{name}}-metric-server'
    spec:
      destination:
          namespace: kube-system
          name: '{{cluster}}'
      project: default
      source:
        repoURL: https://kubernetes-sigs.github.io/metrics-server/
        targetRevision: 3.12.2
        chart: metrics-server
        helm:
          values: |
            resources:
              requests:
                cpu: 100m
                memory: 200Mi