apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vpa
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            name: dev
          # - cluster: cluster-name
  template:
    metadata:
      name: '{{name}}-vpa'
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      destination:
          namespace: vpa
          name: '{{cluster}}'
      syncPolicy:
        automated:
          prune: false           
          selfHeal: true          
        syncOptions:
        - CreateNamespace=true
        
      project: default
      source:
        repoURL: https://charts.fairwinds.com/stable
        targetRevision: 4.6.0
        chart: vpa
        helm:
          values: |
            recommender:
              image: 
                repository: registry.k8s.io/autoscaling/vpa-updater
                tag: "1.2.1"
              extraArgs:
                prometheus-address: http://dev-kube-prometheus-stack-prometheus.monitoring:9090 
                storage: prometheus
            updater:
              enabled: false